"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _home_nuevo from './home-nuevo.bones.json'
import _home_ofertas from './home-ofertas.bones.json'
import _plp_grid from './plp-grid.bones.json'
import _account_wishlist from './account-wishlist.bones.json'
import _pdp from './pdp.bones.json'
import _account_orders from './account-orders.bones.json'
import _admin_kpis from './admin-kpis.bones.json'
import _admin_chart from './admin-chart.bones.json'
import _admin_last_orders from './admin-last-orders.bones.json'
import _admin_customers from './admin-customers.bones.json'
import _admin_stock from './admin-stock.bones.json'
import _admin_promos from './admin-promos.bones.json'

registerBones({
  "home-nuevo": _home_nuevo,
  "home-ofertas": _home_ofertas,
  "plp-grid": _plp_grid,
  "account-wishlist": _account_wishlist,
  "pdp": _pdp,
  "account-orders": _account_orders,
  "admin-kpis": _admin_kpis,
  "admin-chart": _admin_chart,
  "admin-last-orders": _admin_last_orders,
  "admin-customers": _admin_customers,
  "admin-stock": _admin_stock,
  "admin-promos": _admin_promos,
})
